owner: nprasad2077
repo: upptime
sites:
  - name: Google
    url: 'https://www.google.com'
  - name: Wikipedia
    url: 'https://en.wikipedia.org'
  - name: Hacker News
    url: 'https://news.ycombinator.com'
  - name: Portfolio
    url: 'https://nikhil.engineer/'
  - name: NBA Stats
    url: 'https://nba-stats-beryl.vercel.app/'
  - name: Nasa Capstone
    url: 'https://nasa-capstone.vercel.app/'
  - name: ProShop
    url: 'https://proshop-nikhil.herokuapp.com/'
  - name: iPhone GUI
    url: 'https://apple-iphone-gui.netlify.app/'
  - name: Nasa Capstone V1
    url: 'https://github.com/nprasad2077/nasa_capstone'
  - name: Pokemon Match
    url: 'https://nprasad2077.github.io/project-1/lib/index.html'
  - name: Angular Store
    url: 'https://nprasad2077.github.io/storeAngular/'
  - name: NBA GraphQL
    url: 'http://209.38.172.107/graphql/'
  - name: Jupyter NBA
    url: 'https://jupyter-nba-c0195976e8f5.herokuapp.com/'
status-website:
  baseUrl: /upptime
  logoUrl: >-
    https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: >-
    **Upptime** is the open-source uptime monitor and status page, powered
    entirely by GitHub.
  introMessage: >-
    This is a status page that displays real time data. No server required —
    just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: 'https://nprasad2077.github.io/upptime/'
    - title: GitHub
      href: 'https://github.com/$OWNER/$REPO'
