owner: nprasad2077
repo: upptime
sites:
  - name: Google
    url: 'https://www.google.com'
  - name: Wikipedia
    url: 'https://en.wikipedia.org'
  - name: Hacker News
    url: 'https://news.ycombinator.com'
  - name: Portfolio
    url: 'https://nikhil.engineer/'
  - name: NBA Stats
    url: 'https://nba-stats-beryl.vercel.app/'
  - name: Nasa Capstone
    url: 'https://nasa-capstone.vercel.app/'
  - name: ProShop
    url: 'https://proshop-nikhil.herokuapp.com/'
  - name: iPhone GUI
    url: 'https://apple-iphone-gui.netlify.app/'
  - name: Nasa Capstone V1
    url: 'https://github.com/nprasad2077/nasa_capstone'
  - name: Pokemon Match
    url: 'https://nprasad2077.github.io/project-1/lib/index.html'
  - name: Angular Store
    url: 'https://nprasad2077.github.io/storeAngular/'
  - name: NBA GraphQL
    url: 'http://209.38.172.107/graphql/#query=%23%20Welcome%20to%20GraphiQL%0A%23%0A%23%20GraphiQL%20is%20an%20in-browser%20tool%20for%20writing%2C%20validating%2C%20and%0A%23%20testing%20GraphQL%20queries.%0A%23%0A%23%20Type%20queries%20into%20this%20side%20of%20the%20screen%2C%20and%20you%20will%20see%20intelligent%0A%23%20typeaheads%20aware%20of%20the%20current%20GraphQL%20type%20schema%20and%20live%20syntax%20and%0A%23%20validation%20errors%20highlighted%20within%20the%20text.%0A%23%0A%23%20GraphQL%20queries%20typically%20start%20with%20a%20%22%7B%22%20character.%20Lines%20that%20start%0A%23%20with%20a%20%23%20are%20ignored.%0A%23%0A%23%20An%20example%20GraphQL%20query%20might%20look%20like%3A%0A%23%0A%23%20%20%20%20%20%7B%0A%23%20%20%20%20%20%20%20field(arg%3A%20%22value%22)%20%7B%0A%23%20%20%20%20%20%20%20%20%20subField%0A%23%20%20%20%20%20%20%20%7D%0A%23%20%20%20%20%20%7D%0A%23%0A%23%20Keyboard%20shortcuts%3A%0A%23%0A%23%20%20%20Prettify%20query%3A%20%20Shift-Ctrl-P%20(or%20press%20the%20prettify%20button)%0A%23%0A%23%20%20Merge%20fragments%3A%20%20Shift-Ctrl-M%20(or%20press%20the%20merge%20button)%0A%23%0A%23%20%20%20%20%20%20%20%20Run%20Query%3A%20%20Ctrl-Enter%20(or%20press%20the%20play%20button)%0A%23%0A%23%20%20%20%20Auto%20Complete%3A%20%20Ctrl-Space%20(or%20just%20start%20typing)%0A%23%0A%0A'
    __dangerous__insecure: true
  - name: Jupyter NBA
    url: 'https://jupyter-nba-c0195976e8f5.herokuapp.com/'
status-website:
  theme: night
  baseUrl: /upptime
  logoUrl: >-
    https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: >-
    **Upptime** is the open-source uptime monitor and status page, powered
    entirely by GitHub.
  introMessage: >-
    This is a status page that displays real time data. No server required —
    just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: 'https://nprasad2077.github.io/upptime/'
    - title: GitHub
      href: 'https://github.com/$OWNER/$REPO'
